[book]
title = "gbadoc"
author = "The Awesome GBA Dev Contributors"
description = "Documents the workings of the Game Boy Advance hardware"
src = "content"
language = "en"

[build]
build-dir = "target/book"
create-missing = true
